name-template: 'Upcoming release 🌈'
categories:
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🎣 New hooks'
    labels:
      - 'new hook'
  - title: '🛀 Features & Convenience'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '📜 Documentation'
    labels:
      - 'documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
