-   id: no-boms
    name: 'check for BOMs'
    description: 'Forbids files that have a UTF-8, UTF-16, or UTF-32 byte-order mark (BOM).'
    entry: no-boms
    language: python
    types: [ file ]
    stages: [ pre-commit, manual ]
-   id: no-todos
    name: 'check for TODO tags'
    description: 'Forbids files that have a TODO tag (configurable list, by default: TODO, FIXME, XXX).'
    entry: no-todos
    language: python
    types: [ text ]
    stages: [ pre-commit, manual ]
