-   id: cojira
    name: 'cross-check with JIRA when commiting'
    description: 'Cross check referenced ticket status in JIRA'
    entry: cojira
    language: python
    stages: [ prepare-commit-msg, manual ]
-   id: commiticketing
    name: 'prepend commit message with ticket reference'
    description: 'Auto-prepend commit message with ticketing system reference based on current branch name.'
    entry: commiticketing
    language: python
    stages: [ prepare-commit-msg, manual ]
-   id: no-boms
    name: 'check for BOMs'
    description: 'Forbids files that have a UTF-8, UTF-16, or UTF-32 byte-order mark (BOM).'
    entry: no-boms
    language: python
    types: [ file ]
    stages: [ pre-commit, manual ]
-   id: no-todos
    name: 'check for TODO tags'
    description: 'Forbids files that have a TODO tag (configurable list, by default: TODO, FIXME, XXX).'
    entry: no-todos
    language: python
    types: [ text ]
    stages: [ pre-commit, manual ]
-   id: lint-commit-message
    name: 'basic linting for the commit message itself'
    description: 'Check the commit message for best practices based on https://cbea.ms/git-commit/'
    entry: lint-commit-message
    language: python
    stages: [ commit-msg, manual ]
