name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    name: Update release notes
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
